config/routes.rb
Spree::Core::Engine.routes.draw do

  root :to => 'home#index'

  resources :products

  match '/locale/set', :to => 'locale#set'

  resources :states, :only => :index
  resources :countries, :only => :index

  # non-restful checkout stuff
  put '/checkout/update/:state', :to => 'checkout#update', :as => :update_checkout
  get '/checkout/:state', :to => 'checkout#edit', :as => :checkout_state
  get '/checkout', :to => 'checkout#edit' , :as => :checkout

  populate_redirect = redirect do |params, request|
    request.flash[:error] = I18n.t(:populate_get_error)
    request.referer || '/cart'
  end

  get '/orders/populate', :via => :get, :to => populate_redirect

  resources :orders do
    post :populate, :on => :collection
  end

  get '/cart', :to => 'orders#edit', :as => :cart
  put '/cart', :to => 'orders#update', :as => :update_cart
  put '/cart/empty', :to => 'orders#empty', :as => :empty_cart

  # route globbing for pretty nested taxon and product paths
  match '/t/*id', :to => 'taxons#show', :as => :nested_taxons

  namespace :admin do
    get '/search/users', :to => "search#users", :as => :search_users

    resources :adjustments
    resources :zones
    resources :banners do
      member do
        post :dismiss
      end
    end
    resources :countries do
      resources :states
    end
    resources :states
    resources :tax_categories

    resources :products do
      collection do
        get :search
      end

      resources :product_properties do
        collection do
          post :update_positions
        end
      end
      resources :images do
        collection do
          post :update_positions
        end
      end
      member do
        get :clone
      end
      resources :variants do
        collection do
          post :update_positions
        end
      end
    end

    get '/variants/search', :to => "variants#search", :as => :search_variants

    resources :option_types do
      collection do
        post :update_positions
        post :update_values_positions
      end
    end

    delete '/option_values/:id', :to => "option_values#destroy", :as => :option_value

    resources :properties do
      collection do
        get :filtered
      end
    end

    delete '/product_properties/:id', :to => "product_properties#destroy", :as => :product_property

    resources :prototypes do
      member do
        get :select
      end

      collection do
        get :available
      end
    end

    resource :inventory_settings
    resource :image_settings
    resources :google_analytics

    resources :orders do
      member do
        put :fire
        get :fire
        post :resend
      end

      resource :customer, :controller => "orders/customer_details"

      resources :adjustments
      resources :line_items
      resources :shipments do
        member do
          put :fire
        end
      end
      resources :return_authorizations do
        member do
          put :fire
        end
      end
      resources :payments do
        member do
          put :fire
        end
      end
    end

    resource :general_settings do
      collection do
        post :dismiss_alert
      end
    end

    resources :taxonomies do
    	collection do
    		post :update_positions
    	end
      member do
        get :get_children
      end

      resources :taxons
    end

    resources :taxons, :only => [] do
      collection do
        get :search
      end
    end

    resources :reports, :only => [:index, :show] do
      collection do
        get :sales_total
        post :sales_total
      end
    end

    resources :shipping_methods
    resources :shipping_categories
    resources :tax_rates
    resource  :tax_settings
    resources :calculators

    resources :trackers
    resources :payment_methods
    resources :mail_methods do
      member do
        post :testmail
      end
    end
  end

  match '/admin', :to => 'admin/orders#index', :as => :admin

  match '/unauthorized', :to => 'home#unauthorized', :as => :unauthorized
  match '/content/cvv', :to => 'content#cvv', :as => :cvv
  match '/content/*path', :to => 'content#show', :via => :get, :as => :content
end

app/models/spree/image.rb
module Spree
  class Image < Asset
    validates_attachment_presence :attachment
    validate :no_attachment_errors

    attr_accessible :alt, :attachment, :position, :viewable_type, :viewable_id

    has_attached_file :attachment,
                      :styles => { :mini => '48x48>', :small => '100x100>', :product => '240x240>', :large => '600x600>' },
                      :default_style => :product,
                      :url => '/spree/products/:id/:style/:basename.:extension',
                      :path => ':rails_root/public/spree/products/:id/:style/:basename.:extension',
                      :convert_options => { :all => '-strip -auto-orient' }
    # save the w,h of the original image (from which others can be calculated)
    # we need to look at the write-queue for images which have not been saved yet
    after_post_process :find_dimensions

    include Spree::Core::S3Support
    supports_s3 :attachment

    Spree::Image.attachment_definitions[:attachment][:styles] = ActiveSupport::JSON.decode(Spree::Config[:attachment_styles])
    Spree::Image.attachment_definitions[:attachment][:path] = Spree::Config[:attachment_path]
    Spree::Image.attachment_definitions[:attachment][:url] = Spree::Config[:attachment_url]
    Spree::Image.attachment_definitions[:attachment][:default_url] = Spree::Config[:attachment_default_url]
    Spree::Image.attachment_definitions[:attachment][:default_style] = Spree::Config[:attachment_default_style]

    #used by admin products autocomplete
    def mini_url
      attachment.url(:mini, false)
    end

    def find_dimensions
      temporary = attachment.queued_for_write[:original]
      filename = temporary.path unless temporary.nil?
      filename = attachment.path if filename.blank?
      geometry = Paperclip::Geometry.from_file(filename)
      self.attachment_width  = geometry.width
      self.attachment_height = geometry.height
    end

    # if there are errors from the plugin, then add a more meaningful message
    def no_attachment_errors
      unless attachment.errors.empty?
        # uncomment this to get rid of the less-than-useful interrim messages
        # errors.clear
        errors.add :attachment, "Paperclip returned errors for file '#{attachment_file_name}' - check ImageMagick installation or image source file."
        false
      end
    end
  end
end

app/controllers/spree/admin/images_controller.rb
module Spree
  module Admin
    class ImagesController < ResourceController
      before_filter :load_data

      create.before :set_viewable
      update.before :set_viewable
      destroy.before :destroy_before

      private

        def location_after_save
          admin_product_images_url(@product)
        end

        def load_data
          @product = Product.find_by_permalink(params[:product_id])
          @variants = @product.variants.collect do |variant|
            [variant.options_text, variant.id]
          end
          @variants.insert(0, [I18n.t(:all), @product.master.id])
        end

        def set_viewable
          @image.viewable_type = 'Spree::Variant'
          @image.viewable_id = params[:image][:viewable_id]
        end

        def destroy_before
          @viewable = @image.viewable
        end

    end
  end
end

app/helpers/spree/admin/images_helper.rb
module Spree
  module Admin
    module ImagesHelper
      def options_text_for(image)
        if image.viewable.is_a?(Spree::Variant)
          image.viewable.options_text
        else
          "All"
        end
      end
    end
  end
end

app/views/spree/admin/images/_form.html.erb
<div data-hook="admin_image_form_fields">
  <div class="four columns alpha">
    <div data-hook="file" class="field">
      <%= f.label t(:filename) %><br>
      <%= f.file_field :attachment %>
    </div>
    <div data-hook="variant" class="field">
      <%= f.label Spree::Variant.model_name.human %><br>
      <%= f.select :viewable_id, @variants, {}, {:class => 'select2 fullwidth'} %>
    </div>
  </div>
  <div data-hook="alt_text" class="field omega five columns">
    <%= f.label t(:alt_text) %><br>
    <%= f.text_area :alt, :rows => 4, :class => 'fullwidth' %>
  </div>
</div>

<div class="clear"></div>

app/views/spree/admin/images/edit.html.erb
<%= render :partial => 'spree/admin/shared/product_sub_menu' %>

<%= render :partial => 'spree/admin/shared/product_tabs', :locals => { :current => 'Images' } %>

<%= render :partial => 'spree/shared/error_messages', :locals => { :target => @image } %>

<% content_for :page_actions do %>
  <li><%= button_link_to t(:back_to_images_list), admin_product_images_url(@product), :icon => 'icon-arrow-left' %></li>
<% end %>

<%= form_for [:admin, @product, @image], :html => { :multipart => true } do |f| %>
  <fieldset data-hook="edit_image">
    <legend align="center"><%= @image.attachment_file_name%></legend>
    <div data-hook="thumbnail" class="field alpha three columns align-center">
      <%= f.label t(:thumbnail) %><br>
      <%= link_to image_tag(@image.attachment.url(:small)), @image.attachment.url(:product) %>
    </div>
    <div class="nine columns omega">
      <%= render :partial => 'form', :locals => { :f => f } %>  
    </div>
    <div class="clear"></div>
    <div class="form-buttons filter-actions actions" data-hook="buttons">
      <%= button t(:update), 'icon-refresh' %>
      <span class="or"><%= t(:or) %></span>
      <%= link_to t(:cancel), admin_product_images_url(@product), :id => 'cancel_link', :class => 'button icon-remove' %>
    </div>
  </fieldset>
<% end %>

app/views/spree/admin/images/index.html.erb
<%= render :partial => 'spree/admin/shared/product_sub_menu' %>

<%= render :partial => 'spree/admin/shared/product_tabs', :locals => {:current => 'Images'} %>

<% content_for :page_actions do %>
  <li><%= link_to_with_icon('icon-plus', t(:new_image), new_admin_product_image_url(@product), :id => 'new_image_link', :class => 'button') %></li>
<% end %>

<div id="images" data-hook></div>

<% unless @product.images.any? || @product.variant_images.any? %>
  <div class="no-objects-found">
    <%= t(:no_images_found) %>.
  </div>
<% else %>
  <table class="index sortable" data-hook="images_table" data-sortable-link="<%= update_positions_admin_product_images_url(@product) %>">
    <colgroup>
      <col style="width: 5%">
      <col style="width: 10%">
      <col style="width: 25%">
      <col style="width: 45%">
      <col style="width: 15%">
    </colgroup>
    <thead>
      <tr data-hook="images_header">
        <th colspan="2"><%= t(:thumbnail) %></th>
        <% if @product.has_variants? %>
          <th><%= Spree::Variant.model_name.human %></th>
        <% end %>
        <th><%= t(:alt_text) %></th>
        <th class="actions"></th>
      </tr>
    </thead>

    <tbody>
      <% (@product.images + @product.variant_images).each do |image| %>
        <tr id="<%= spree_dom_id image %>" data-hook="images_row" class="<%= cycle('odd', 'even')%>">
          <td class="no-border">
            <span class="handle"></span>
          </td>
          <td>
            <%= link_to image_tag(image.attachment.url(:mini)), image.attachment.url(:product) %>
          </td>
          <td><%= options_text_for(image) %></td>
          <td><%= image.alt %></td>
          <td class="actions">
            <%= link_to_with_icon 'icon-edit', t(:edit), edit_admin_product_image_url(@product, image), :no_text => true, :data => {:action => 'edit'} %>
            <%= link_to_delete image, { :url => admin_product_image_url(@product, image), :no_text => true } %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

app/views/spree/admin/images/new.html.erb
<%= form_for [:admin, @product, @image], :html => { :multipart => true } do |f| %>
  <fieldset data-hook="new_image">
    <legend align="center"><%= t(:new_image) %></legend>

      <%= render :partial => 'form', :locals => { :f => f } %>
    
      <div class="form-buttons filter-actions actions" data-hook="buttons">
        <%= button t(:update), 'icon-refresh' %>
        <span class="or"><%= t(:or) %></span>
        <%= link_to_with_icon 'icon-remove', t(:cancel), admin_product_images_url(@product), :id => 'cancel_link', :class => 'button' %>
      </div>
  </fieldset>
<% end %>

<%= javascript_include_tag 'admin/images/new.js' %>