config/routes.rb
Spree::Core::Engine.routes.draw do

  root :to => 'home#index'

  resources :products

  match '/locale/set', :to => 'locale#set'

  resources :states, :only => :index
  resources :countries, :only => :index

  # non-restful checkout stuff
  put '/checkout/update/:state', :to => 'checkout#update', :as => :update_checkout
  get '/checkout/:state', :to => 'checkout#edit', :as => :checkout_state
  get '/checkout', :to => 'checkout#edit' , :as => :checkout

  populate_redirect = redirect do |params, request|
    request.flash[:error] = I18n.t(:populate_get_error)
    request.referer || '/cart'
  end

  get '/orders/populate', :via => :get, :to => populate_redirect

  resources :orders do
    post :populate, :on => :collection
  end

  get '/cart', :to => 'orders#edit', :as => :cart
  put '/cart', :to => 'orders#update', :as => :update_cart
  put '/cart/empty', :to => 'orders#empty', :as => :empty_cart

  # route globbing for pretty nested taxon and product paths
  match '/t/*id', :to => 'taxons#show', :as => :nested_taxons

  namespace :admin do
    get '/search/users', :to => "search#users", :as => :search_users

    resources :adjustments
    resources :zones
    resources :banners do
      member do
        post :dismiss
      end
    end
    resources :countries do
      resources :states
    end
    resources :states
    resources :tax_categories

    resources :products do
      collection do
        get :search
      end

      resources :product_properties do
        collection do
          post :update_positions
        end
      end
      resources :images do
        collection do
          post :update_positions
        end
      end
      member do
        get :clone
      end
      resources :variants do
        collection do
          post :update_positions
        end
      end
    end

    get '/variants/search', :to => "variants#search", :as => :search_variants

    resources :option_types do
      collection do
        post :update_positions
        post :update_values_positions
      end
    end

    delete '/option_values/:id', :to => "option_values#destroy", :as => :option_value

    resources :properties do
      collection do
        get :filtered
      end
    end

    delete '/product_properties/:id', :to => "product_properties#destroy", :as => :product_property

    resources :prototypes do
      member do
        get :select
      end

      collection do
        get :available
      end
    end

    resource :inventory_settings
    resource :image_settings
    resources :google_analytics

    resources :orders do
      member do
        put :fire
        get :fire
        post :resend
      end

      resource :customer, :controller => "orders/customer_details"

      resources :adjustments
      resources :line_items
      resources :shipments do
        member do
          put :fire
        end
      end
      resources :return_authorizations do
        member do
          put :fire
        end
      end
      resources :payments do
        member do
          put :fire
        end
      end
    end

    resource :general_settings do
      collection do
        post :dismiss_alert
      end
    end

    resources :taxonomies do
    	collection do
    		post :update_positions
    	end
      member do
        get :get_children
      end

      resources :taxons
    end

    resources :taxons, :only => [] do
      collection do
        get :search
      end
    end

    resources :reports, :only => [:index, :show] do
      collection do
        get :sales_total
        post :sales_total
      end
    end

    resources :shipping_methods
    resources :shipping_categories
    resources :tax_rates
    resource  :tax_settings
    resources :calculators

    resources :trackers
    resources :payment_methods
    resources :mail_methods do
      member do
        post :testmail
      end
    end
  end

  match '/admin', :to => 'admin/orders#index', :as => :admin

  match '/unauthorized', :to => 'home#unauthorized', :as => :unauthorized
  match '/content/cvv', :to => 'content#cvv', :as => :cvv
  match '/content/*path', :to => 'content#show', :via => :get, :as => :content
end

app/models/spree/order/checkout.rb
module Spree
  class Order < ActiveRecord::Base
    module Checkout
      def self.included(klass)
        klass.class_eval do
          class_attribute :next_event_transitions
          class_attribute :previous_states
          class_attribute :checkout_flow
          class_attribute :checkout_steps

          def self.checkout_flow(&block)
            if block_given?
              @checkout_flow = block
              define_state_machine!
            else
              @checkout_flow
            end
          end

          def self.define_state_machine!
            # Needs to be an ordered hash to preserve flow order
            self.checkout_steps = ActiveSupport::OrderedHash.new
            self.next_event_transitions = []
            self.previous_states = [:cart]

            # Build the checkout flow using the checkout_flow defined either
            # within the Order class, or a decorator for that class.
            #
            # This method may be called multiple times depending on if the
            # checkout_flow is re-defined in a decorator or not.
            instance_eval(&checkout_flow)

            klass = self

            # To avoid a ton of warnings when the state machine is re-defined
            StateMachine::Machine.ignore_method_conflicts = true
            # To avoid multiple occurrences of the same transition being defined
            # On first definition, state_machines will not be defined
            state_machines.clear if respond_to?(:state_machines)
            state_machine :state, :initial => :cart do
              klass.next_event_transitions.each { |t| transition(t.merge(:on => :next)) }

              # Persist the state on the order
              after_transition do |order|
                order.state = order.state
                order.save
              end

              event :cancel do
                transition :to => :canceled, :if => :allow_cancel?
              end

              event :return do
                transition :to => :returned, :from => :awaiting_return, :unless => :awaiting_returns?
              end

              event :resume do
                transition :to => :resumed, :from => :canceled, :if => :allow_resume?
              end

              event :authorize_return do
                transition :to => :awaiting_return
              end

              before_transition :to => :complete do |order|
                begin
                  order.process_payments! if order.payment_required?
                rescue Spree::Core::GatewayError
                  !!Spree::Config[:allow_checkout_on_gateway_error]
                end
              end

              before_transition :to => :delivery, :do => :remove_invalid_shipments!

              after_transition :to => :complete, :do => :finalize!
              after_transition :to => :delivery, :do => :create_tax_charge!
              after_transition :to => :resumed,  :do => :after_resume
              after_transition :to => :canceled, :do => :after_cancel

              after_transition :from => :delivery,  :do => :create_shipment!
            end
          end

          def self.go_to_state(name, options={})
            self.checkout_steps[name] = options
            previous_states.each do |state|
              add_transition({:from => state, :to => name}.merge(options))
            end
            if options[:if]
              self.previous_states << name
            else
              self.previous_states = [name]
            end
          end

          def self.remove_transition(options={})
            if transition = find_transition(options)
              self.next_event_transitions.delete(transition)
            end
          end

          def self.find_transition(options={})
            self.next_event_transitions.detect do |transition|
              transition[options[:from].to_sym] == options[:to].to_sym
            end
          end

          def self.next_event_transitions
            @next_event_transitions ||= []
          end

          def self.checkout_steps
            @checkout_steps ||= ActiveSupport::OrderedHash.new
          end

          def self.add_transition(options)
            self.next_event_transitions << { options.delete(:from) => options.delete(:to) }.merge(options)
          end

          def checkout_steps
            checkout_steps = []
            # TODO: replace this with each_with_object once Ruby 1.9 is standard
            self.class.checkout_steps.each do |step, options|
              if options[:if]
                next unless options[:if].call(self)
              end
              checkout_steps << step
            end
            steps = checkout_steps.map(&:to_s)
            # Ensure there is always a complete step
            steps << "complete" unless steps.include?("complete")
            steps
          end
        end
      end
    end
  end
end

app/controllers/spree/admin/orders/customer_details_controller.rb
module Spree
  module Admin
    module Orders
      class CustomerDetailsController < Spree::Admin::BaseController
        before_filter :load_order

        def show
          edit
          render :action => :edit
        end

        def edit
          country_id = Address.default.country.id
          @order.build_bill_address(:country_id => country_id) if @order.bill_address.nil?
          @order.build_ship_address(:country_id => country_id) if @order.ship_address.nil?
        end

        def update
          if @order.update_attributes(params[:order])
            shipping_method = @order.available_shipping_methods(:front_end).first
            if shipping_method
              @order.shipping_method = shipping_method

              if params[:user_id].present?
                @order.user_id = params[:user_id]
                @order.user true
              end
              @order.save
              @order.create_shipment!
              flash[:success] = t('customer_details_updated')
              redirect_to edit_admin_order_shipment_path(@order, @order.shipment)
            else
              flash[:error] = t('errors.messages.no_shipping_methods_available')
              redirect_to admin_order_customer_path(@order)
            end
          else
            render :action => :edit
          end

        end

        private

          def load_order
            @order = Order.find_by_number!(params[:order_id], :include => :adjustments)
          end

      end
    end
  end
end

app/controllers/spree/admin/orders_controller.rb
module Spree
  module Admin
    class OrdersController < Spree::Admin::BaseController
      require 'spree/core/gateway_error'
      before_filter :initialize_order_events
      before_filter :load_order, :only => [:show, :edit, :update, :fire, :resend]

      respond_to :html

      def index
        params[:q] ||= {}
        params[:q][:completed_at_not_null] ||= '1' if Spree::Config[:show_only_complete_orders_by_default]
        @show_only_completed = params[:q][:completed_at_not_null].present?
        params[:q][:s] ||= @show_only_completed ? 'completed_at desc' : 'created_at desc'

        # As date params are deleted if @show_only_completed, store
        # the original date so we can restore them into the params
        # after the search
        created_at_gt = params[:q][:created_at_gt]
        created_at_lt = params[:q][:created_at_lt]

        params[:q].delete(:inventory_units_shipment_id_null) if params[:q][:inventory_units_shipment_id_null] == "0"

        if !params[:q][:created_at_gt].blank?
          params[:q][:created_at_gt] = Time.zone.parse(params[:q][:created_at_gt]).beginning_of_day rescue ""
        end

        if !params[:q][:created_at_lt].blank?
          params[:q][:created_at_lt] = Time.zone.parse(params[:q][:created_at_lt]).end_of_day rescue ""
        end

        if @show_only_completed
          params[:q][:completed_at_gt] = params[:q].delete(:created_at_gt)
          params[:q][:completed_at_lt] = params[:q].delete(:created_at_lt)
        end

        @search = Order.accessible_by(current_ability, :index).ransack(params[:q])
        @orders = @search.result.includes([:user, :shipments, :payments]).
          page(params[:page]).
          per(params[:per_page] || Spree::Config[:orders_per_page])

        # Restore dates
        params[:q][:created_at_gt] = created_at_gt
        params[:q][:created_at_lt] = created_at_lt

        respond_with(@orders)
      end

      def show
        respond_with(@order)
      end

      def new
        @order = Order.create
        respond_with(@order)
      end

      def edit
        respond_with(@order)
      end

      def update
        return_path = nil
        if @order.update_attributes(params[:order]) && @order.line_items.present?
          @order.update!
          unless @order.complete?
            # Jump to next step if order is not complete.
            return_path = admin_order_customer_path(@order)
          else
            # Otherwise, go back to first page since all necessary information has been filled out.
            return_path = admin_order_path(@order)
          end
        else
          @order.errors.add(:line_items, t('errors.messages.blank')) if @order.line_items.empty?
        end

        respond_with(@order) do |format|
          format.html do
            if return_path
              redirect_to return_path
            else
              render :action => :edit
            end
          end
        end
      end

      def fire
        # TODO - possible security check here but right now any admin can before any transition (and the state machine
        # itself will make sure transitions are not applied in the wrong state)
        event = params[:e]
        if @order.send("#{event}")
          flash[:success] = t(:order_updated)
        else
          flash[:error] = t(:cannot_perform_operation)
        end
      rescue Spree::Core::GatewayError => ge
        flash[:error] = "#{ge.message}"
      ensure
        respond_with(@order) { |format| format.html { redirect_to :back } }
      end

      def resend
        OrderMailer.confirm_email(@order, true).deliver
        flash[:success] = t(:order_email_resent)

        respond_with(@order) { |format| format.html { redirect_to :back } }
      end

      private

        def load_order
          @order = Order.find_by_number!(params[:id], :include => :adjustments) if params[:id]
          authorize! params[:action], @order
        end

        # Used for extensions which need to provide their own custom event links on the order details view.
        def initialize_order_events
          @order_events = %w{cancel resume}
        end

        def model_class
          Spree::Order
        end
    end
  end
end

app/controllers/spree/orders_controller.rb
module Spree
  class OrdersController < Spree::StoreController
    ssl_required :show

    rescue_from ActiveRecord::RecordNotFound, :with => :render_404
    helper 'spree/products'

    respond_to :html

    def show
      @order = Order.find_by_number!(params[:id])
      respond_with(@order)
    end

    def update
      @order = current_order
      if @order.update_attributes(params[:order])
        @order.line_items = @order.line_items.select {|li| li.quantity > 0 }
        fire_event('spree.order.contents_changed')
        respond_with(@order) do |format|
          format.html do
            if params.has_key?(:checkout)
              @order.next_transition.run_callbacks
              redirect_to checkout_state_path(@order.checkout_steps.first)
            else
              redirect_to cart_path
            end
          end
        end
      else
        respond_with(@order)
      end
    end

    # Shows the current incomplete order from the session
    def edit
      @order = current_order(true)
      associate_user
    end

    # Adds a new item to the order (creating a new order if none already exists)
    def populate
      populator = Spree::OrderPopulator.new(current_order(true), current_currency)
      if populator.populate(params.slice(:products, :variants, :quantity))
        fire_event('spree.cart.add')
        fire_event('spree.order.contents_changed')
        respond_with(@order) do |format|
          format.html { redirect_to cart_path }
        end
      else
        flash[:error] = populator.errors.full_messages.join(" ")
        redirect_to :back
      end
    end

    def empty
      if @order = current_order
        @order.empty!
      end

      redirect_to spree.cart_path
    end

    def accurate_title
      @order && @order.completed? ? "#{Order.model_name.human} #{@order.number}" : t(:shopping_cart)
    end
  end
end

app/helpers/spree/admin/orders_helper.rb
module Spree
  module Admin
    module OrdersHelper
      # Renders all the extension partials that may have been specified in the extensions
      def event_links
        links = []
        @order_events.sort.each do |event|
          if @order.send("can_#{event}?")
            links << button_link_to(t(event), fire_admin_order_url(@order, :e => event),
                                    :method => :put,
                                    :icon => "icon-#{event}",
                                    :data => { :confirm => t(:order_sure_want_to, :event => t(event)) })
          end
        end
        links.join('&nbsp;').html_safe
      end
    end
  end
end

app/views/spree/admin/orders/_add_product.html.erb
<%= render :partial => "spree/admin/variants/autocomplete", :formats => :js %>

<div id="add-line-item" data-hook>
  <fieldset>
    <legend align="center"><%= t(:add_product) %></legend>
    
    <div data-hook="add_product_name" class="field eight columns alpha">
      <%= label_tag :add_product_name, t(:name_or_sku) %>
      <%= hidden_field_tag :add_variant_id, "", :class => "variant_autocomplete fullwidth" %>
    </div>
    
    <div data-hook="add_quantity" class="field two columns">
      <%= label_tag :add_quantity, t(:qty) %>
      <%= number_field_tag :add_quantity,  1, :min => 0 %>
    </div>
    
    <div data-hook="add_button" class="actions two columns omega">
      <%= link_to_with_icon 'icon-plus', t(:add), admin_order_line_items_url(@order), 
                  :method => :post,
                  :id => 'add_line_item_to_order',
                  :class => 'button fullwidth',
                  'data-update' => 'order-form-wrapper' %>
    </div>

  </fieldset>
</div>

app/views/spree/admin/orders/_form.html.erb
 <div data-hook="admin_order_form_fields">
  <% if @line_item.try(:errors).present? %>
    <%= render :partial => 'spree/shared/error_messages', :locals => { :target => @line_item } %>
  <% end %>
  
  <%= form_for @order, :url => admin_order_url(@order), :method => :put do |f| %>
    <fieldset class="no-border-top">
      <%= f.hidden_field :number %>
      <table class="index">
        <colgroup>
           <col style="width: 49%;">
           <col style="width: 14%;">
           <col style="width: 10%;">
           <col style="width: 14%;">
           <col style="width: 8%;">
        </colgroup>
        <thead id="line-items">
          <tr data-hook="admin_order_form_line_items_headers">
            <th><%= t(:item_description) %></th>
            <th class="price"><%= t(:price) %></th>
            <th class="qty"><%= t(:qty) %></th>
            <th class="total"><span><%= t(:total) %></span></th>
            <th class="orders-actions actions" data-hook="admin_order_form_line_items_header_actions"></th>
          </tr>        
        </thead>
        <tbody data-hook="admin_order_form_line_items">
          <%= f.fields_for :line_items do |li_form| %>
            <%= render :partial => 'spree/admin/orders/line_item', :locals => { :f => li_form } %>
          <% end %>
        </tbody>
        <tbody id="subtotal" data-hook="admin_order_form_subtotal" class="no-border-top">
          <tr id="subtotal-row">
            <td colspan="3"><b><%= t(:subtotal) %>:</b></td>
            <td class="total align-center"><span><%= @order.display_item_total %></span></td>
            <td class="actions"></td>
          </tr>
        </tbody>
        <tbody id="order-charges" data-hook="admin_order_form_adjustments" class="no-border-top">
          <% @order.adjustments.eligible.each do |adjustment| %>
            <tr>
              <td colspan="3"><strong><%= adjustment.label %>:</strong></td>
              <td class="total align-center"><span><%= adjustment.display_amount %></span></td>
              <td class="actions"></td>
            </tr>
          <% end %>
        </tbody>
        <tbody id="order-total" data-hook="admin_order_form_total" class="grand-total no-border-top">
          <tr>
            <td colspan="3"><b><%= t(:order_total) %>:</b></td>
            <td class="total align-center"><span id="order_total"><%= @order.display_total %></span></td>
            <td class="actions"></td>
          </tr>
        </tbody>
      </table>

      <div class="filter-actions actions" data-hook="admin_order_form_buttons">
        <%= button t(:update), 'icon-refresh' %>
        <span class="or"><%= t(:or) %></span>
        <%= link_to_with_icon 'button icon-arrow-left', t(:back), admin_orders_url %>
      </div>
    </fieldset>
  <% end %>

  <%= javascript_tag do -%>
    <%= render :partial => 'spree/admin/shared/update_order_state', :handlers => [:js] %>
  <% end -%>
</div>

app/views/spree/admin/orders/_line_item.html.erb
<tr id="<%= spree_dom_id(f.object) %>" data-hook="admin_order_form_line_item_row" class="<%= cycle('odd', 'even')%>">
  <td><%=f.object.variant.product.name%> <%= "(#{f.object.variant.options_text})" unless f.object.variant.option_values.empty? %></td>
  <td class="price align-center"><%= f.object.variant.display_amount %></td>
  <td class="qty"><%= f.number_field :quantity, :min => 0, :class => "qty" %></td>
  <td class="total align-center"><%= f.object.display_amount %></td>
  <td data-hook="admin_order_form_line_item_actions" class="actions">
    <%= link_to_delete f.object, {:url => admin_order_line_item_url(@order.number, f.object), :no_text => true} %>
  </td>
</tr>

app/views/spree/admin/orders/edit.html.erb
<%= csrf_meta_tags %>
<% content_for :page_actions do %>
  <li><%= event_links %></li>
  <li><%= button_link_to t(:resend), resend_admin_order_url(@order), :method => :post, :icon => 'icon-email' %></li>
  <li><%= button_link_to t(:back_to_orders_list), admin_orders_path, :icon => 'icon-arrow-left' %></li>
<% end %>

<%= render :partial => 'spree/admin/shared/order_tabs', :locals => { :current => 'Order Details' } %>

<div data-hook="admin_order_edit_header">
  <%= render :partial => 'spree/shared/error_messages', :locals => { :target => @order } %>
</div>

<%= render :partial => 'add_product' %>

<div data-hook="admin_order_edit_form">
  <div id="order-form-wrapper">
    <%= render :partial => 'form', :locals => { :order => @order } %>
  </div>
</div>

<% content_for :head do %>
  <%= javascript_tag 'var expand_variants = true;' %>
<% end %>

app/views/spree/admin/orders/index.html.erb
<% content_for :page_title do %>
  <%= t(:listing_orders) %>
<% end %>

<% content_for :page_actions do %>
  <li>
    <%= button_link_to t(:new_order), new_admin_order_url, :icon => 'icon-plus', :id => 'admin_new_order' %>
  </li>
<% end %>

<% content_for :table_filter_title do %>
  <%= t(:search) %>
<% end %>

<% content_for :table_filter do %>
  <div data-hook="admin_orders_index_search">
    <%= search_form_for [:admin, @search] do |f| %>
      <div class="field-block alpha four columns">          
        <div class="date-range-filter field">
          <%= label_tag nil, t(:date_range) %>
          <div class="date-range-fields">
            <%= f.text_field :created_at_gt, :class => 'datepicker datepicker-from', :value => params[:q][:created_at_gt], :placeholder => t(:start) %>
            
            <span class="range-divider">
              <i class="icon-arrow-right"></i>
            </span>
              
            <%= f.text_field :created_at_lt, :class => 'datepicker datepicker-to', :value => params[:q][:created_at_lt], :placeholder => t(:stop) %>
          </div>
        </div>

        <div class="field">
          <%= label_tag nil, t(:status) %>
          <%= f.select :state_eq, Spree::Order.state_machines[:state].states.collect {|s| [t("order_state.#{s.name}"), s.value]}, {:include_blank => true}, :class => 'select2' %>  
        </div>
      </div>
      
      <div class="four columns">
        <div class="field">
          <%= label_tag nil, t(:order_number) %>
          <%= f.text_field :number_cont %>
        </div>
        <div class="field">
          <%= label_tag nil, t(:email) %>
          <%= f.email_field :email_cont %>
        </div>
      </div>
      
      <div class="four columns">
        <div class="field">
          <%= label_tag nil, t(:first_name_begins_with) %>
          <%= f.text_field :bill_address_firstname_start, :size => 25 %>
        </div>
        <div class="field">
          <%= label_tag nil, t(:last_name_begins_with) %>
          <%= f.text_field :bill_address_lastname_start, :size => 25%>
        </div>
      </div>
      
      <div class="omega four columns">
        <div class="field checkbox">
          <label>
            <%= f.check_box :completed_at_not_null, {:checked => @show_only_completed}, '1', '' %>
            <%= t(:show_only_complete_orders) %>
          </label>
        </div>

        <div class="field checkbox">
          <label>
            <%= f.check_box :inventory_units_shipment_id_null, { }, '1', '0' %>
            <%= t(:show_only_unfulfilled_orders) %>
          </label>
        </div>
      </div>

      <div class="clearfix"></div>

      <div class="actions filter-actions">
        <div data-hook="admin_orders_index_search_buttons">
          <%= button t(:filter_results), 'icon-search' %>
        </div>
      </div>
    <% end %>    
  </div>
<% end %>

<table class="index responsive" id="listing_orders" data-hook>
  <colgroup>
     <col style="width: 16%;">
     <col style="width: 10%;">
     <col style="width: 13%;">
     <col style="width: 13%;">
     <col style="width: 13%;">
     <col style="width: 17%;">
     <col style="width: 10%;">
     <col style="width: 8%;">
  </colgroup>
  <thead>
    <tr data-hook="admin_orders_index_headers">
      <% if @show_only_completed %>
        <th><%= sort_link @search, :completed_at, t(:completed_at, :scope => 'activerecord.attributes.spree/order') %></th>
      <% else %>
        <th><%= sort_link @search, :created_at,   t(:created_at, :scope => 'activerecord.attributes.spree/order') %></th>
      <% end %>
      <th><%= sort_link @search, :number,         t(:number, :scope => 'activerecord.attributes.spree/order') %></th>
      <th><%= sort_link @search, :state,          t(:state, :scope => 'activerecord.attributes.spree/order') %></th>
      <th><%= sort_link @search, :payment_state,  t(:payment_state, :scope => 'activerecord.attributes.spree/order') %></th>
      <th><%= sort_link @search, :shipment_state, t(:shipment_state, :scope => 'activerecord.attributes.spree/order') %></th>
      <th><%= sort_link @search, :email,          t(:email, :scope => 'activerecord.attributes.spree/order') %></th>
      <th><%= sort_link @search, :total,          t(:total, :scope => 'activerecord.attributes.spree/order') %></th>
      <th data-hook="admin_orders_index_header_actions" class="actions"></th>
    </tr>
  </thead>
  <tbody>
  <% @orders.each do |order| %>
    <tr data-hook="admin_orders_index_rows" class="state-<%= order.state.downcase %> <%= cycle('odd', 'even') %>">
      <td class="align-center"><%= l (@show_only_completed ? order.completed_at : order.created_at).to_date %></td>
      <td><%= link_to order.number, admin_order_path(order) %></td>
      <td class="align-center"><span class="state <%= order.state.downcase %>"><%= t("order_state.#{order.state.downcase}") %></span></td>
      <td class="align-center"><span class="state <%= order.payment_state %>"><%= link_to t("payment_states.#{order.payment_state}"), admin_order_payments_path(order) if order.payment_state %></span></td>
      <td class="align-center"><span class="state <%= order.shipment_state %>"><%= link_to t("shipment_states.#{order.shipment_state}"), admin_order_shipments_path(order) if order.shipment_state %></span></td>
      <td><%= mail_to order.email %></td>
      <td class="align-center"><%= order.display_total %></td>
      <td class='actions align-center' data-hook="admin_orders_index_row_actions">
        <%= link_to_edit_url edit_admin_order_path(order), :title => "admin_edit_#{dom_id(order)}", :no_text => true %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

<%= paginate @orders %>

app/views/spree/admin/orders/new.html.erb
<% content_for :page_title do %>
  <%= t(:new) %>
<% end %>

<% content_for :page_actions do %>
  <li><%= button_link_to t(:back_to_orders_list), spree.admin_orders_path, :icon => 'icon-arrow-left' %></li>
<% end %>

<%= render :partial => 'spree/admin/shared/order_tabs', :locals => { :current => 'Order Details' } %>

<%= csrf_meta_tags %>

<div data-hook="admin_order_new_header">
  <%= render :partial => 'spree/shared/error_messages', :locals => { :target => @order } %>
</div>

<%= render :partial => 'add_product' %>

<% unless @order.line_items.any? %>
  <div data-hook="admin_order_new_form">
    <div id="order-form-wrapper">
      <%= render :partial => 'form' %>
    </div>
  </div>
<% else %>
<% end %>

<% content_for :head do %>
  <%= javascript_tag 'var expand_variants = true;' %>
<% end %>

app/views/spree/admin/orders/show.html.erb
<% content_for :page_actions do %>
  <li>
    <%= button_link_to t(:cancel), fire_admin_order_url(@order.number, { :e => 'cancel' }), :icon => 'icon-trash', :data => { :confirm => t(:are_you_sure) } if @order.can_cancel? %>  
  </li>
  <li>
    <%= button_link_to t(:edit), edit_admin_order_url(@order.number), :icon => 'icon-edit' %>
  </li>
  <li><%= button_link_to t(:back_to_orders_list), admin_orders_path, :icon => 'icon-arrow-left' %></li>
<% end %>


<%= render :partial => 'spree/admin/shared/order_tabs', :locals => { :current => 'Order Details' } %>

<div data-hook="admin_order_show_addresses" class="row">
  <% if @order.bill_address %>
    <fieldset class="alpha six columns no-border-bottom">
      <legend align="center"><%= t(:bill_address) %></legend>
      <div class="align-center">
        <%= render :partial => 'spree/admin/shared/address', :locals => { :address => @order.bill_address } %>  
      </div>
    </fieldset>
  <% end %>
  <% if @order.ship_address %>
    <fieldset class="omega six columns no-border-bottom">
      <legend align="center"><%= t(:ship_address) %></legend>
      <div class="align-center">
        <%= render :partial => 'spree/admin/shared/address', :locals => { :address => @order.ship_address } %>
      </div>
    </fieldset>
    <% end %>
</div>

<div data-hook="admin_order_show_details">
  <%= render :partial => 'spree/admin/shared/order_details', :locals => { :order => @order } %>
</div>