config/routes.rb
Spree::Core::Engine.routes.draw do

  root :to => 'home#index'

  resources :products

  match '/locale/set', :to => 'locale#set'

  resources :states, :only => :index
  resources :countries, :only => :index

  # non-restful checkout stuff
  put '/checkout/update/:state', :to => 'checkout#update', :as => :update_checkout
  get '/checkout/:state', :to => 'checkout#edit', :as => :checkout_state
  get '/checkout', :to => 'checkout#edit' , :as => :checkout

  populate_redirect = redirect do |params, request|
    request.flash[:error] = I18n.t(:populate_get_error)
    request.referer || '/cart'
  end

  get '/orders/populate', :via => :get, :to => populate_redirect

  resources :orders do
    post :populate, :on => :collection
  end

  get '/cart', :to => 'orders#edit', :as => :cart
  put '/cart', :to => 'orders#update', :as => :update_cart
  put '/cart/empty', :to => 'orders#empty', :as => :empty_cart

  # route globbing for pretty nested taxon and product paths
  match '/t/*id', :to => 'taxons#show', :as => :nested_taxons

  namespace :admin do
    get '/search/users', :to => "search#users", :as => :search_users

    resources :adjustments
    resources :zones
    resources :banners do
      member do
        post :dismiss
      end
    end
    resources :countries do
      resources :states
    end
    resources :states
    resources :tax_categories

    resources :products do
      collection do
        get :search
      end

      resources :product_properties do
        collection do
          post :update_positions
        end
      end
      resources :images do
        collection do
          post :update_positions
        end
      end
      member do
        get :clone
      end
      resources :variants do
        collection do
          post :update_positions
        end
      end
    end

    get '/variants/search', :to => "variants#search", :as => :search_variants

    resources :option_types do
      collection do
        post :update_positions
        post :update_values_positions
      end
    end

    delete '/option_values/:id', :to => "option_values#destroy", :as => :option_value

    resources :properties do
      collection do
        get :filtered
      end
    end

    delete '/product_properties/:id', :to => "product_properties#destroy", :as => :product_property

    resources :prototypes do
      member do
        get :select
      end

      collection do
        get :available
      end
    end

    resource :inventory_settings
    resource :image_settings
    resources :google_analytics

    resources :orders do
      member do
        put :fire
        get :fire
        post :resend
      end

      resource :customer, :controller => "orders/customer_details"

      resources :adjustments
      resources :line_items
      resources :shipments do
        member do
          put :fire
        end
      end
      resources :return_authorizations do
        member do
          put :fire
        end
      end
      resources :payments do
        member do
          put :fire
        end
      end
    end

    resource :general_settings do
      collection do
        post :dismiss_alert
      end
    end

    resources :taxonomies do
    	collection do
    		post :update_positions
    	end
      member do
        get :get_children
      end

      resources :taxons
    end

    resources :taxons, :only => [] do
      collection do
        get :search
      end
    end

    resources :reports, :only => [:index, :show] do
      collection do
        get :sales_total
        post :sales_total
      end
    end

    resources :shipping_methods
    resources :shipping_categories
    resources :tax_rates
    resource  :tax_settings
    resources :calculators

    resources :trackers
    resources :payment_methods
    resources :mail_methods do
      member do
        post :testmail
      end
    end
  end

  match '/admin', :to => 'admin/orders#index', :as => :admin

  match '/unauthorized', :to => 'home#unauthorized', :as => :unauthorized
  match '/content/cvv', :to => 'content#cvv', :as => :cvv
  match '/content/*path', :to => 'content#show', :via => :get, :as => :content
end

app/models/spree/variant.rb
module Spree
  class Variant < ActiveRecord::Base
    belongs_to :product, :touch => true

    delegate_belongs_to :product, :name, :description, :permalink, :available_on,
                        :tax_category_id, :shipping_category_id, :meta_description,
                        :meta_keywords, :tax_category

    attr_accessible :name, :presentation, :cost_price, :lock_version,
                    :position, :on_demand, :on_hand, :option_value_ids,
                    :product_id, :option_values_attributes, :price,
                    :weight, :height, :width, :depth, :sku, :cost_currency

    has_many :inventory_units
    has_many :line_items
    has_and_belongs_to_many :option_values, :join_table => :spree_option_values_variants
    has_many :images, :as => :viewable, :order => :position, :dependent => :destroy

    has_one :default_price,
      :class_name => 'Spree::Price',
      :conditions => proc { { :currency => Spree::Config[:currency] } },
      :dependent => :destroy

    delegate_belongs_to :default_price, :display_price, :display_amount, :price, :price=, :currency if Spree::Price.table_exists?

    has_many :prices,
      :class_name => 'Spree::Price',
      :dependent => :destroy

    validate :check_price
    validates :price, :numericality => { :greater_than_or_equal_to => 0 }, :presence => true, :if => proc { Spree::Config[:require_master_price] }
    validates :cost_price, :numericality => { :greater_than_or_equal_to => 0, :allow_nil => true } if self.table_exists? && self.column_names.include?('cost_price')
    validates :count_on_hand, :numericality => true

    before_validation :set_cost_currency
    after_save :process_backorders
    after_save :save_default_price
    after_save :recalculate_product_on_hand, :if => :is_master?

    # default variant scope only lists non-deleted variants
    scope :deleted, lambda { where('deleted_at IS NOT NULL') }

    def self.active(currency = nil)
      joins(:prices).where(:deleted_at => nil).where('spree_prices.currency' => currency || Spree::Config[:currency]).where('spree_prices.amount IS NOT NULL')
    end

    # Returns number of inventory units for this variant (new records haven't been saved to database, yet)
    def on_hand
      if Spree::Config[:track_inventory_levels] && !self.on_demand
        count_on_hand 
      else
        (1.0 / 0) # Infinity
      end
    end

    # set actual attribute
    def on_hand=(new_level)
      if !Spree::Config[:track_inventory_levels]
        raise 'Cannot set on_hand value when Spree::Config[:track_inventory_levels] is false'
      else
        self.count_on_hand = new_level unless self.on_demand
      end
    end

    def cost_price=(price)
      self[:cost_price] = parse_price(price) if price.present?
    end

    # returns number of units currently on backorder for this variant.
    def on_backorder
      inventory_units.with_state('backordered').size
    end

    # returns true if at least one inventory unit of this variant is "on_hand"
    def in_stock?
      if Spree::Config[:track_inventory_levels] && !self.on_demand
        on_hand > 0 
      else
        true
      end
    end
    alias in_stock in_stock?

    # returns true if this variant is allowed to be placed on a new order
    def available?
      Spree::Config[:track_inventory_levels] ? (Spree::Config[:allow_backorders] || in_stock? || self.on_demand) : true
    end

    def options_text
      values = self.option_values.joins(:option_type).order("#{Spree::OptionType.table_name}.position asc")

      values.map! do |ov|
        "#{ov.option_type.presentation}: #{ov.presentation}"
      end

      values.to_sentence({ :words_connector => ", ", :two_words_connector => ", " })
    end

    def gross_profit
      cost_price.nil? ? 0 : (price - cost_price)
    end

    # use deleted? rather than checking the attribute directly. this
    # allows extensions to override deleted? if they want to provide
    # their own definition.
    def deleted?
      deleted_at
    end

    def set_option_value(opt_name, opt_value)
      # no option values on master
      return if self.is_master

      option_type = Spree::OptionType.where(:name => opt_name).first_or_initialize do |o|
        o.presentation = opt_name
        o.save!
      end

      current_value = self.option_values.detect { |o| o.option_type.name == opt_name }

      unless current_value.nil?
        return if current_value.name == opt_value
        self.option_values.delete(current_value)
      else
        # then we have to check to make sure that the product has the option type
        unless self.product.option_types.include? option_type
          self.product.option_types << option_type
          self.product.save
        end
      end

      option_value = Spree::OptionValue.where(:option_type_id => option_type.id, :name => opt_value).first_or_initialize do |o|
        o.presentation = opt_value
        o.save!
      end

      self.option_values << option_value
      self.save
    end

    def option_value(opt_name)
      self.option_values.detect { |o| o.option_type.name == opt_name }.try(:presentation)
    end

    def on_demand=(on_demand)
      self[:on_demand] = on_demand
      if on_demand
        inventory_units.with_state('backordered').each(&:fill_backorder)
      end
    end

    def has_default_price?
      !self.default_price.nil?
    end

    def price_in(currency)
      prices.select{ |price| price.currency == currency }.first || Spree::Price.new(:variant_id => self.id, :currency => currency)
    end

    def amount_in(currency)
      price_in(currency).try(:amount)
    end

    private

      def process_backorders
        if count_changes = changes['count_on_hand']
          new_level = count_changes.last

          if Spree::Config[:track_inventory_levels] && !self.on_demand
            new_level = new_level.to_i

            # update backorders if level is positive
            if new_level > 0
              # fill backordered orders before creating new units
              backordered_units = inventory_units.with_state('backordered')
              backordered_units.slice(0, new_level).each(&:fill_backorder)
              new_level -= backordered_units.length
            end

            self.update_attribute_without_callbacks(:count_on_hand, new_level)
          end
        end
      end

      # Ensures a new variant takes the product master price when price is not supplied
      def check_price
        if price.nil? && Spree::Config[:require_master_price]
          raise 'No master variant found to infer price' unless (product && product.master)
          raise 'Must supply price for variant or master.price for product.' if self == product.master
          self.price = product.master.price
        end
        if currency.nil?
          self.currency = Spree::Config[:currency]
        end
      end

      # strips all non-price-like characters from the price, taking into account locale settings
      def parse_price(price)
        return price unless price.is_a?(String)

        separator, delimiter = I18n.t([:'number.currency.format.separator', :'number.currency.format.delimiter'])
        non_price_characters = /[^0-9\-#{separator}]/
        price.gsub!(non_price_characters, '') # strip everything else first
        price.gsub!(separator, '.') unless separator == '.' # then replace the locale-specific decimal separator with the standard separator if necessary

        price.to_d
      end

      def recalculate_product_on_hand
        on_hand = product.on_hand
        if Spree::Config[:track_inventory_levels] && on_hand != (1.0 / 0) # Infinity
          product.update_column(:count_on_hand, on_hand)
        end
      end

      def save_default_price
        default_price.save if default_price && (default_price.changed? || default_price.new_record?)
      end

      def set_cost_currency
        self.cost_currency = Spree::Config[:currency] if cost_currency.nil? || cost_currency.empty?
      end
  end
end

require_dependency 'spree/variant/scopes'

app/models/spree/variant/scopes.rb
module Spree
  class Variant < ActiveRecord::Base
    #FIXME WARNING tested only under sqlite and postgresql
    scope :descend_by_popularity, order("COALESCE((SELECT COUNT(*) FROM  #{LineItem.quoted_table_name} GROUP BY #{LineItem.quoted_table_name}.variant_id HAVING #{LineItem.quoted_table_name}.variant_id = #{Variant.quoted_table_name}.id), 0) DESC")

    class << self
      # Returns variants that match a given option value
      #
      # Example:
      #
      # product.variants_including_master.has_option(OptionType.find_by_name("shoe-size"),OptionValue.find_by_name("8"))
      def has_option(option_type, *option_values)
        option_types = OptionType.table_name

        option_type_conditions = case option_type
        when OptionType then { "#{option_types}.name" => option_type.name }
        when String     then { "#{option_types}.name" => option_type }
        else                 { "#{option_types}.id"   => option_type }
        end

        relation = joins(:option_values => :option_type).where(option_type_conditions)

        option_values_conditions = option_values.each do |option_value|
          option_value_conditions = case option_value
          when OptionValue then { "#{OptionValue.table_name}.name" => option_value.name }
          when String      then { "#{OptionValue.table_name}.name" => option_value }
          else                  { "#{OptionValue.table_name}.id"   => option_value }
          end
          relation = relation.where(option_value_conditions)
        end

        relation
      end

      alias_method :has_options, :has_option
    end
  end
end

app/controllers/spree/admin/variants_controller.rb
module Spree
  module Admin
    class VariantsController < ResourceController
      belongs_to 'spree/product', :find_by => :permalink
      create.before :create_before
      new_action.before :new_before

      def index
        respond_with(collection)
      end

      def search
        search_params = { :product_name_cont => params[:q], :sku_cont => params[:q] }
        @variants = Spree::Variant.ransack(search_params.merge(:m => 'or')).result
      end

      # override the destory method to set deleted_at value
      # instead of actually deleting the product.
      def destroy
        @variant = Variant.find(params[:id])
        @variant.deleted_at = Time.now()
        if @variant.save
          flash[:success] = I18n.t('notice_messages.variant_deleted')
        else
          flash[:success] = I18n.t('notice_messages.variant_not_deleted')
        end

        respond_with(@variant) do |format|
          format.html { redirect_to admin_product_variants_url(params[:product_id]) }
          format.js  { render_js_for_destroy }
        end
      end

      protected

        def create_before
          option_values = params[:new_variant]
          option_values.each_value {|id| @object.option_values << OptionValue.find(id)}
          @object.save
        end


        def new_before
          @object.attributes = @object.product.master.attributes.except('id', 'created_at', 'deleted_at',
                                                                        'sku', 'is_master', 'count_on_hand')
          # Shallow Clone of the default price to populate the price field.
          @object.default_price = @object.product.master.default_price.clone
        end

        def collection
          @deleted = (params.key?(:deleted) && params[:deleted] == "on") ? "checked" : ""

          if @deleted.blank?
            @collection ||= super
          else
            @collection ||= Variant.where(:product_id => parent.id).deleted
          end
          @collection
        end
    end
  end
end

app/views/spree/admin/variants/_autocomplete.js.erb
<script type='text/template' id='variant_autocomplete_template'>
  <div class='variant-autocomplete-item'>
    <figure class='variant-image'>
      {{#if variant.image }}
        <img src='{{variant.image}}' />
      {{ else }}
        <img src='/assets/noimage/mini.png' />
      {{/if}}
    </figure>

    <div class='variant-details'>

      <h6 class="variant-name">{{variant.name}}</h6>

      <ul class='variant-data'>
        <li class='variant-sku'><strong>{{t 'sku'}}:</strong> {{variant.sku}}</li>
        <li class='variant-on_hand'><strong>{{t 'on_hand' }}:</strong> {{variant.count_on_hand}}</li>
      </ul>

      {{#if variant.option_values}}
        <ul class='variant-options'>
          {{#each variant.option_values}}
            <li><strong>{{this.option_type.presentation}}:</strong> {{this.presentation}}</li>
          {{/each}}
        </ul>
      {{/if}}

    </div>
  </div>
</script>

app/views/spree/admin/variants/_form.html.erb
<div data-hook="admin_variant_form_fields" class="label-block left six columns alpha">
  
  <div data-hook="variants">
    <% @product.options.each do |option| %>
      <div class="field" data-hook="presentation">
        <%= label :new_variant, option.option_type.presentation %>
        <% if @variant.new_record? %>
          <%= select(:new_variant, option.option_type.presentation,
            option.option_type.option_values.collect {|ov| [ ov.presentation, ov.id ] },
            {}, {:class => 'select2 fullwidth'})
          %>
        <% else %>
          <% if opt = @variant.option_values.detect {|o| o.option_type == option.option_type }.try(:presentation) %>
            <%= text_field(:new_variant,  option.option_type.presentation, :value => opt, :disabled => 'disabled', :class => 'fullwidth') %>
          <% end %>
        <% end %>
      </div>
    <% end %>

    <div class="field" data-hook="sku">
      <%= f.label :sku, t(:sku) %>
      <%= f.text_field :sku, :class => 'fullwidth' %>
    </div>

    <div class="field" data-hook="price">
      <%= f.label :price, t(:price) %>
      <%= f.text_field :price, :value => number_to_currency(@variant.price, :unit => ''), :class => 'fullwidth' %>
    </div>

    <div class="field" data-hook="cost_price">
      <%= f.label :cost_price, t(:cost_price) %>
      <%= f.text_field :cost_price, :value => number_to_currency(@variant.cost_price, :unit => ''), :class => 'fullwidth' %>
    </div>

    <% if Spree::Config[:track_inventory_levels] %>
      <div class="field checkbox" data-hook="on_hand">
        <label>
          <%= f.check_box :on_demand %>
          <%= t(:on_demand) %>
        </label>
      </div>
      <div class="field" data-hook="on_hand">
        <%= f.label :on_hand, t(:on_hand) %>
        <%= f.text_field :on_hand, :class => 'fullwidth' %>
      </div>
    <% end %>
  </div>
</div>



<div class="right six columns omega label-block" data-hook="admin_variant_form_additional_fields">
  <% [:weight, :height, :width, :depth].each do |field| %>
    <div class="field" data-hook="<%= field %>"><%= f.label field, t(field) %>
      <% value = number_with_precision(@variant.send(field), :precision => 2) %>
      <%= f.text_field field, :value => value, :class => 'fullwidth' %>
    </div>
  <% end %>
</div>

<div class="clear"></div>

app/views/spree/admin/variants/edit.html.erb
<%= render :partial => 'spree/admin/shared/product_sub_menu' %>

<%= render :partial => 'spree/admin/shared/product_tabs', :locals => { :current => 'Variants' } %>

<%= render :partial => 'spree/shared/error_messages', :locals => { :target => @variant } %>

<%= form_for [:admin, @product, @variant] do |f| %>
  <div data-hook="admin_variant_edit_form">
    <%= render :partial => 'form', :locals => { :f => f } %>
  </div>

  <%= render :partial => 'spree/admin/shared/edit_resource_links' %>
<% end %>

app/views/spree/admin/variants/index.html.erb
<%= render :partial => 'spree/admin/shared/product_sub_menu' %>

<%= render :partial => 'spree/admin/shared/product_tabs', :locals => {:current => 'Variants'} %>

<%# Place for new variant form %>
<div id="new_variant" data-hook></div>

<% if @variants.any? %>
  <table class="index sortable" data-sortable-link="<%= update_positions_admin_product_variants_path(@product) %>">
    <colgroup>
      <col style="width: 5%" />
      <col style="width: 25%" />
      <col style="width: 20%" />
      <col style="width: 20%" />
      <col style="width: 15%" />
      <col style="width: 15%" />
    </colgroup>
    <thead data-hook="variants_header">
      <tr>
        <th colspan="2"><%= t(:options) %></th>
        <th><%= t(:price) %></th>
        <th><%= t(:sku) %></th>
        <th><%= t(:on_hand) %></th>
        <th class="actions"></th>
      </tr>
    </thead>
    <tbody>
    <% @variants.each do |variant| %>
      <!-- you can skip variant with no options: that's just the default variant that all products have -->
      <% next if variant.option_values.empty? %>
        <tr id="<%= spree_dom_id variant %>" <%= 'style="color:red;"' if variant.deleted? %> data-hook="variants_row" class="<%= cycle('odd', 'even')%>">
          <td class="no-border">
            <span class="handle"></span>
          </td>
          <td><%= variant.options_text %></td>
          <td class="align-center"><%= variant.display_price %></td>
          <td class="align-center"><%= variant.sku %></td>
          <td class="align-center"><%= variant.on_hand %></td>
          <td class="actions">
            <%= link_to_edit(variant, :no_text => true) unless variant.deleted? %>
            &nbsp;
            <%= link_to_delete(variant, :no_text => true) unless variant.deleted? %>
          </td>
        </tr>
      <% end %>
      <% unless @product.has_variants? %>
        <tr><td colspan="5"><%= t(:none) %></td></tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <div class="alpha twelve columns no-objects-found"><%= t(:no_results)%>.</div>
<% end %>

<% if @product.empty_option_values? %>
  <p class='first_add_option_types no-objects-found' data-hook="first_add_option_types">
    <%= t(:to_add_variants_you_must_first_define) %>
    <%= link_to t(:option_types), admin_product_url(@product) %>
    <%= t(:and) %>
    <%= link_to t(:option_values), admin_option_types_url %>
  </p>
<% else %>
  <% content_for :page_actions do %>
    <ul class="inline-menu" data-hook="toolbar">
      <li id="new_var_link" data-hook>
        <%= link_to_with_icon('icon-plus', 
                              t(:new_variant), 
                              new_admin_product_variant_url(@product), 
                              :remote => :true, 
                              :'data-update' => 'new_variant', 
                              :class => 'button'
                             ) %>
      </li>
      <li><%= link_to_with_icon('icon-filter', @deleted.blank? ? t(:show_deleted) : t(:show_active), admin_product_variants_url(@product, :deleted => @deleted.blank? ? "on" : "off"), :class => 'button') %></li>
    </ul>
  <% end %>

<% end %>

app/views/spree/admin/variants/new.html.erb
<%= render :partial => 'spree/shared/error_messages', :locals => { :target => @variant } %>

<%= form_for [:admin, @product, @variant] do |f| %>
  <fieldset data-hook="admin_variant_new_form">
    <legend align="center"><%= t(:new_variant) %></legend>
    <%= render :partial => 'form', :locals => { :f => f } %>
    <%= render :partial => 'spree/admin/shared/new_resource_links' %>
  </fieldset>
<% end %>

app/views/spree/admin/variants/new.js.erb
$("#new_variant").html('<%= escape_javascript(render :template => 'spree/admin/variants/new', :formats => [:html], :handlers => [:erb]) %>');
$(".select2").select2();
$("#new_var_link").hide();